views:
  - title: Overview
    path: overview
    badges: []
    cards: []
  - title: Basement
    path: basement
    badges: []
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.basement_door
        title: Doors
      - type: entities
        entities:
          - entity: light.laundry_overhead
          - entity: light.office_lamp
          - entity: switch.basement_sensi_pot
          - entity: light.play_area_ceiling
        title: Lights
        show_header_toggle: false
  - title: Ground
    path: ground
    badges: []
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.front_door
          - entity: binary_sensor.guest_toilet_door
          - entity: binary_sensor.basement_door
          - entity: binary_sensor.back_door
        title: Doors
      - type: entities
        entities:
          - entity: light.lounge_lamp
          - entity: light.lounge_desk_lamp
          - entity: light.dining_lamp
          - entity: switch.front_door
        title: Lights
      - type: media-control
        entity: media_player.living_room_speaker
  - title: Upstairs
    path: upstairs
    badges: []
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.master_bedroom_door
          - entity: binary_sensor.bathroom_door
          - entity: binary_sensor.sam_bedroom_door
          - entity: binary_sensor.boys_bedroom_door
        title: Doors
      - type: entities
        entities:
          - entity: light.master_bedside
          - entity: light.master_lamp
          - entity: switch.master_bedroom
          - entity: light.sam_s_bedside
          - entity: light.boys_room_lamp
        title: Lights
  - title: External
    path: external
    badges: []
    cards:
      - type: entities
        entities:
          - entity: light.external_front
          - entity: light.external_back
        show_header_toggle: false
        title: Lights
      - type: entities
        entities:
          - entity: binary_sensor.front_door
          - entity: binary_sensor.back_door
        title: Doors
