views:
  - title: Default
    path: default
    badges:
      - entity: person.richard_niemand
      - entity: person.kelsie
      - entity: person.sam
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                min: 0
                max: 100
                entity: sensor.richard_pixel4_battery_level
                name: Richard
                unit: '%'
                severity:
                  green: 51
                  yellow: 50
                  red: 20
              - type: gauge
                min: 0
                max: 100
                entity: sensor.kelsie_samsung_battery_level
                name: Kelsie
                unit: '%'
                severity:
                  green: 51
                  yellow: 50
                  red: 20
              - type: gauge
                entity: sensor.sam_phone_battery_level
                min: 0
                max: 100
                name: Sam
                unit: '%'
                severity:
                  green: 51
                  yellow: 50
                  red: 20
          - type: history-graph
            entities:
              - entity: sensor.richard_pixel4_battery_level
                name: Richard
              - entity: sensor.kelsie_samsung_battery_level
                name: Kelsie
              - entity: sensor.sam_phone_battery_level
                name: Sam
            hours_to_show: 4
            refresh_interval: 30
title: Overview
