views:
  - title: Default
    path: default
    badges:
      - entity: person.richard_niemand
      - entity: person.kelsie
      - entity: person.sam
    cards:
      - type: glance
        entities:
          - entity: binary_sensor.front_door
            name: Front
          - entity: binary_sensor.guest_toilet_door
            name: Guest Loo
          - entity: binary_sensor.basement_door
            name: Basement
          - entity: binary_sensor.back_door
            name: Back
          - entity: binary_sensor.master_bedroom_door
            name: Master
          - entity: binary_sensor.bathroom_door
            name: Bathroom
          - entity: binary_sensor.sam_bedroom_door
            name: Sam
          - entity: binary_sensor.boys_bedroom_door
            name: Boys
        show_state: false
        columns: 4
        title: Tracked Doors
        state_color: true
title: Overview
