- id: '1603234118314'
  alias: 'MQTT (Light.Toggle) Basement: Storage Nook'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - data: {}
    entity_id: light.hue_white_lamp_1_2
    service: light.toggle
  mode: single
- id: '1603234257759'
  alias: 'MQTT (Light.Toggle) Basement: Play Area'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - data: {}
    entity_id: light.play_area_overhead
    service: light.toggle
  mode: single
- id: '1603234565632'
  alias: 'MQTT (Light.Toggle) Upstairs: Spare Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - data: {}
    entity_id: light.spare_room_lamp
    service: light.toggle
  mode: single
- id: '1603234724795'
  alias: 'MQTT (Light.Toggle) Upstairs: Spare Room (Night Light)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A834''
      }}'
  action:
  - data:
      brightness_pct: 5
      entity_id: light.spare_room_lamp
      transition: 2
    entity_id: light.spare_room_lamp
    service: light.turn_on
  mode: single
- id: '1603234823037'
  alias: 'MQTT (Light.Toggle) Upstairs: Master Wall'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A832''
      }}'
  action:
  - data: {}
    entity_id: switch.master_bedroom
    service: switch.toggle
  mode: single
- id: '1603234955913'
  alias: 'MQTT (Switch.Toggle) Upstairs: Master Fan'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A831''
      }}'
  action:
  - data: {}
    entity_id: switch.master_fan
    service: switch.toggle
  mode: single
- id: '1603485536575'
  alias: Testing
  description: ''
  trigger:
  - entity_id: binary_sensor.spare_room_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 06:00:00
    before: '15:00:00'
    condition: time
  action:
  - data:
      data:
        priority: 1
      message: Spare room door is open
      title: Spare Room Door
    service: notify.pushover_richard
  mode: single
