- id: '1605573563132'
  alias: 'Remote: Kelsie 01 (A)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - service: light.toggle
    data:
      entity_id: light.boys_room
    entity_id: light.boys_room
  mode: single
- id: '1605573675948'
  alias: 'Remote: Kelsie 01 (B)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A834''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.boys_room
      transition: 2
    entity_id: light.boys_room
  mode: single
- id: '1605573790636'
  alias: 'Remote: Kelsie 01 (C)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A832''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_bedroom
  mode: single
- id: '1605573868284'
  alias: 'Remote: Kelsie 01 (D)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A831''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_fan
  mode: single
- id: '1605574020388'
  alias: 'Remote: Basement Landing (Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.play_area_ceiling
  mode: single
- id: '1605574074821'
  alias: 'Remote: Basement Landing (Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.storage_nook
  mode: single
- id: '1605574149445'
  alias: 'Remote: Basement Office (Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.office_lamp
  mode: single
- id: '1605574198853'
  alias: 'Remote: Basement Office (Middle)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A8''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.basement_sensi_pot
  mode: single
- id: '1605574248758'
  alias: 'Remote: Basement Office (Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.laundry_overhead
  mode: single
- id: '1605574369085'
  alias: 'Remote: Sam 01 (Top Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56801''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      entity_id: light.sam_s_room
      transition: 1
    entity_id: light.sam_s_room
  mode: single
- id: '1605574436357'
  alias: 'Remote: Sam 01 (Bottom Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56802''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.sam_s_room
      transition: 2
    entity_id: light.sam_s_room
  mode: single
- id: '1605574490493'
  alias: 'Remote: Sam 01 (Top Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56804''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.sam_s_room
  mode: single
- id: '1608332045332'
  alias: 'Remote: Keychains (A)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''FF5F71''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.external_lights
  mode: single
- id: '1608598270136'
  alias: Simple Testing
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: Hello World 2
      cache: false
  mode: single
- id: '1608680666885'
  alias: 'Kids: (Alert) Basement Door'
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.basement_door
  condition:
  - condition: state
    state: 'on'
    entity_id: input_boolean.monitor_basement_door
  action:
  - service: mqtt.publish
    data:
      topic: lights/flash/master
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: The basement door is open
      cache: false
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The basement door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The basement door is open
  mode: single
- id: '1608680942953'
  alias: 'Kids: (Alert) Boys Room Door'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_bedroom_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.monitor_kids_doors
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: lights/flash/master
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: The boys room door is open
      cache: false
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The boys room door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The boys room door is open
  mode: single
- id: '1608681011645'
  alias: 'Kids: (Alert) Ericas Room Door'
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.sam_bedroom_door
  condition:
  - condition: state
    entity_id: input_boolean.monitor_kids_doors
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: lights/flash/master
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: Ericas door is open
      cache: false
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: Ericas door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: Ericas door is open
  mode: single
- id: '1608681064979'
  alias: 'Kids: (Alert) Back Door'
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.back_door
  condition:
  - condition: state
    entity_id: input_boolean.monitor_kids_doors
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: lights/flash/master
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: The back door is open
      cache: false
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The back door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The back door is open
  mode: single
- id: '1608681105604'
  alias: 'Kids: (Alert) Front Door'
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.front_door
  condition:
  - condition: state
    entity_id: input_boolean.monitor_kids_doors
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: lights/flash/master
  - service: tts.google_translate_say
    data:
      entity_id: media_player.bedroom_speaker
      message: The front door is open
      cache: false
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The front door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The front door is open
  mode: single
