- id: '1603736277244'
  alias: 'Pushover <HIGH> Doors: Basement (Ahem)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  mode: single
- id: '1603813904430'
  alias: 'RF-04-L [Light.Toggle] Basement: Office'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.basement_office
  mode: single
- id: '1603813978471'
  alias: 'RF-04-R [Light.Toggle] Basement: Laundry'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.laundry
  mode: single
- id: '1603814354836'
  alias: 'RF-04-M [Switch.Toggle] Basement: Sensi Pot'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A8''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.basement_sensi_pot
  mode: single
- id: '1605282084623'
  alias: 'Alert: Boys Room Door (Afternoon)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_room_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: 00:00:01
    before: 07:00:00
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  mode: single
- id: '1605282537767'
  alias: 'Alert: Boys Room Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_room_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '23:00:00'
    before: 07:00:00
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605282710795'
  alias: 'Alert: Basement Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '23:30:00'
    before: 07:00:00
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Basement door is open
      title: 'Door: Basement'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Basement door is open
      title: 'Door: Basement'
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605282806991'
  alias: 'Alert: Front Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '23:00:00'
    before: 07:00:00
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Front door is open
      title: 'Door: Front'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Front door is open
      title: 'Door: Front'
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605282963530'
  alias: 'Alert: Back Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '23:30:00'
    before: 07:00:00
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Back door is open
      title: 'Door: Back'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Back door is open
      title: 'Door: Back'
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605298176837'
  alias: 'Light: Sam Bedside - Dim (RF)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56802''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.sam_s_bedside
      transition: 2
    entity_id: light.sam_s_bedside
  mode: single
- id: '1605298312196'
  alias: 'Light: Sam Bedside - Toggle (RF)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56804''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.sam_s_bedside
  mode: single
- id: '1605298395686'
  alias: 'Light: Sam Bedside - Bright (RF)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56801''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      entity_id: light.sam_s_bedside
      transition: 1
    entity_id: light.sam_s_bedside
  mode: single
- id: '1605573563132'
  alias: 'Remote: Kelsie 01 (A)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - service: light.toggle
    data:
      entity_id: light.boys_room
    entity_id: light.boys_room
  mode: single
- id: '1605573675948'
  alias: 'Remote: Kelsie 01 (B)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A834''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.boys_room
      transition: 2
    entity_id: light.boys_room
  mode: single
- id: '1605573790636'
  alias: 'Remote: Kelsie 01 (C)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A832''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_bedroom
  mode: single
- id: '1605573868284'
  alias: 'Remote: Kelsie 01 (D)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A831''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_fan
  mode: single
- id: '1605574020388'
  alias: 'Remote: Basement Landing (Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.play_area_ceiling
  mode: single
- id: '1605574074821'
  alias: 'Remote: Basement Landing (Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.storage_nook
  mode: single
