- id: '1603234118314'
  alias: 'MQTT (Light.Toggle) Basement: Storage Nook'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - data: {}
    entity_id: light.hue_white_lamp_1_2
    service: light.toggle
  mode: single
- id: '1603234257759'
  alias: 'MQTT (Light.Toggle) Basement: Play Area'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - data: {}
    entity_id: light.play_area_overhead
    service: light.toggle
  mode: single
