- id: '1603736277244'
  alias: 'Pushover <HIGH> Doors: Basement (Ahem)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  mode: single
- id: '1605573563132'
  alias: 'Remote: Kelsie 01 (A)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - service: light.toggle
    data:
      entity_id: light.boys_room
    entity_id: light.boys_room
  mode: single
- id: '1605573675948'
  alias: 'Remote: Kelsie 01 (B)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A834''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.boys_room
      transition: 2
    entity_id: light.boys_room
  mode: single
- id: '1605573790636'
  alias: 'Remote: Kelsie 01 (C)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A832''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_bedroom
  mode: single
- id: '1605573868284'
  alias: 'Remote: Kelsie 01 (D)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A831''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.master_fan
  mode: single
- id: '1605574020388'
  alias: 'Remote: Basement Landing (Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.play_area_ceiling
  mode: single
- id: '1605574074821'
  alias: 'Remote: Basement Landing (Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.storage_nook
  mode: single
- id: '1605574149445'
  alias: 'Remote: Basement Office (Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.office_lamp
  mode: single
- id: '1605574198853'
  alias: 'Remote: Basement Office (Middle)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A8''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.basement_sensi_pot
  mode: single
- id: '1605574248758'
  alias: 'Remote: Basement Office (Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.laundry_overhead
  mode: single
- id: '1605574369085'
  alias: 'Remote: Sam 01 (Top Right)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56801''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      entity_id: light.sam_s_room
      transition: 1
    entity_id: light.sam_s_room
  mode: single
- id: '1605574436357'
  alias: 'Remote: Sam 01 (Bottom Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56802''
      }}'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 5
      entity_id: light.sam_s_room
      transition: 2
    entity_id: light.sam_s_room
  mode: single
- id: '1605574490493'
  alias: 'Remote: Sam 01 (Top Left)'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56804''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.sam_s_room
  mode: single
- id: '1605575366377'
  alias: 'Alert: Boys Room Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_room_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  - condition: time
    after: 00:00:01
    before: 07:00:00
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Boys Room Door
      message: The boys room door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Boys Room Door
      message: The boys room door is open
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605575448927'
  alias: 'Alert: Boys Room Door (Afternoon Nap)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_room_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  - condition: time
    after: '11:45:00'
    before: '13:30:00'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Boys Room Door
      message: The boys room door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Boys Room Door
      message: The boys room door is open
  mode: single
- id: '1605575530192'
  alias: 'Alert: Basement Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  - condition: time
    after: 00:00:01
    before: 07:00:00
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The basement door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Basement Door
      message: The basement door is open
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605575595342'
  alias: 'Alert: Front Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  - condition: time
    after: 00:00:01
    before: 07:00:00
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Front Door
      message: The front door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Front Door
      message: The front door is open
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
- id: '1605575664246'
  alias: 'Alert: Back Door (Early Morning)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.kids_here
    state: 'on'
  - condition: time
    after: 00:00:01
    before: 07:00:00
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      title: Back Door
      message: The back door is open
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      title: Back Door
      message: The back door is open
  - service: script.flash_lights_master_bedroom
    data: {}
  mode: single
