- id: '1603233943916'
  alias: Toggle Basement Office Light
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - data: {}
    entity_id: light.basement_office
    service: light.toggle
  mode: single
