- id: '1603234118314'
  alias: 'RF-03-R [Light.Toggle] Basement: Storage Nook'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB2''
      }}'
  action:
  - data: {}
    entity_id: light.hue_white_lamp_1_2
    service: light.toggle
  mode: single
- id: '1603234257759'
  alias: 'RF-03-L [Light.Toggle] Basement: Play Area'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''3EAEB1''
      }}'
  action:
  - data: {}
    entity_id: light.play_area_overhead
    service: light.toggle
  mode: single
- id: '1603234565632'
  alias: 'RF-02-A [Light.Toggle] Upstairs: Spare Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A838''
      }}'
  action:
  - data: {}
    entity_id: light.spare_room_lamp
    service: light.toggle
  mode: single
- id: '1603234724795'
  alias: 'RF-02-B [Light.NightLight] Upstairs: Spare Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A834''
      }}'
  action:
  - data:
      brightness_pct: 5
      entity_id: light.spare_room_lamp
      transition: 2
    entity_id: light.spare_room_lamp
    service: light.turn_on
  mode: single
- id: '1603234823037'
  alias: 'RF-02-C [Switch.Toggle] Upstairs: Master Wall'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A832''
      }}'
  action:
  - data: {}
    entity_id: switch.master_bedroom_light_switch
    service: switch.toggle
  mode: single
- id: '1603234955913'
  alias: 'RF-02-D [Switch.Toggle] Upstairs: Master Fan'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''19A831''
      }}'
  action:
  - data: {}
    entity_id: switch.master_fan
    service: switch.toggle
  mode: single
- id: '1603489757466'
  alias: 'Pushover <HIGH> Door: Boys Room (Early Morning)'
  description: ''
  trigger:
  - entity_id: binary_sensor.spare_room_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 01:00:00
    before: 07:00:00
    condition: time
  action:
  - data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
    service: notify.pushover_richard
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  - service: script.master_bedroom_notify_lights
    data: {}
  mode: single
- id: '1603490104373'
  alias: 'Pushover <HIGH> Doors: Basement (Early Morning)'
  description: ''
  trigger:
  - entity_id: binary_sensor.basement_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: time
    after: 01:00:00
    before: 07:00:00
  action:
  - data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
    service: notify.pushover_richard
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  - service: script.master_bedroom_notify_lights
    data: {}
  mode: single
- id: '1603491114440'
  alias: 'Pushover <HIGH> Doors: Front (Early Morning)'
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 01:00:00
    before: 07:00:00
    condition: time
  action:
  - data:
      data:
        priority: 1
        sound: siren
      message: Front Door is open!
      title: 'Door: Front'
    service: notify.pushover_richard
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: siren
      message: Front Door is open!
      title: 'Door: Front'
  mode: single
- id: '1603493124055'
  alias: 'RF-01-TL [Light.Toggle] Upstairs: Sam''s Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56804''
      }}'
  action:
  - data: {}
    entity_id: light.sam_s_light
    service: light.toggle
  mode: single
- id: '1603493241122'
  alias: 'RF-01-TR [Light.Bright] Upstairs: Sam''s Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56801''
      }}'
  action:
  - data:
      brightness_pct: 100
      entity_id: light.sam_s_light
      transition: 1
    entity_id: light.sam_s_light
    service: light.turn_on
  mode: single
- id: '1603493338675'
  alias: 'RF-01-BL [Light.NightLight] Upstairs: Sam''s Room'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''E56802''
      }}'
  action:
  - data:
      brightness_pct: 5
      entity_id: light.sam_s_light
      transition: 2
    entity_id: light.sam_s_light
    service: light.turn_on
  mode: single
- id: '1603736277244'
  alias: 'Pushover <HIGH> Doors: Basement (Ahem)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: The basement door is open
      title: 'Door: Basement'
  mode: single
- id: '1603813904430'
  alias: 'RF-04-L [Light.Toggle] Basement: Office'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A1''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.basement_office
  mode: single
- id: '1603813978471'
  alias: 'RF-04-R [Light.Toggle] Basement: Laundry'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A2''
      }}'
  action:
  - service: light.toggle
    data: {}
    entity_id: light.laundry
  mode: single
- id: '1603814354836'
  alias: 'RF-04-M [Switch.Toggle] Basement: Sensi Pot'
  description: ''
  trigger:
  - platform: mqtt
    topic: tele/sonoff_rf/RESULT
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''RfReceived''][''Data''] == ''1992A8''
      }}'
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.basement_sensi_pot
  mode: single
- id: '1605282084623'
  alias: 'Pushover: Boys Room Door (Afternoon)'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.boys_room_door
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '11:45:00'
    before: '16:00:00'
  action:
  - service: notify.pushover_richard
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  - service: notify.pushover_kelsie
    data:
      data:
        priority: 1
        sound: tugboat
      message: Boys room door is open
      title: 'Door: Boys Room'
  mode: single
