
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret mysql_connection

tplink:
  discovery: false
  switch:
    - host: 192.168.0.67
    - host: 192.168.0.77

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pass

weather:
  - platform: darksky
    api_key: !secret darksky_apikey

sabnzbd:
  api_key: !secret sabnzbd_apikey
  host: !secret sabnzbd_host
  port: !secret sabnzbd_port
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

sensor:
  - platform: radarr
    api_key: !secret radarr_apikey
    host: !secret radarr_host
    port: !secret radarr_port
    monitored_conditions:
      - upcoming
      - movies
      - status
    days: 2

  - platform: worldclock
    time_zone: Africa/Johannesburg
    name: Durban
      
panel_iframe:
  blog:
    title: Home Control
    icon: mdi:playlist-check
    url: http://nas.richardn.ca/clean-home/

binary_sensor:
  - platform: ping
    host: 192.168.0.64
    count: 2
    scan_interval: 60
    name: Printer
  - platform: ping
    host: 192.168.0.100
    count: 2
    scan_interval: 60
    name: ubuntu-db
  - platform: ping
    host: 192.168.0.67
    count: 2
    scan_interval: 60
    name: bedroom-fan-plug
  - platform: ping
    host: 192.168.0.127
    count: 2
    scan_interval: 60
    name: hue-hub
  - platform: ping
    host: 192.168.0.101
    count: 2
    scan_interval: 60
    name: ubuntu-apps1
  - platform: ping
    host: 192.168.0.213
    count: 2
    scan_interval: 60
    name: lounge-ghome
  - platform: ping
    host: 192.168.0.200
    count: 2
    scan_interval: 60
    name: sonoff-rf
  - platform: ping
    host: 192.168.0.50
    count: 2
    scan_interval: 60
    name: nas
  - platform: ping
    host: 192.168.0.79
    count: 2
    scan_interval: 60
    name: rn-gamer
  - platform: ping
    host: 192.168.0.68
    count: 2
    scan_interval: 60
    name: richard-ipad
  - platform: ping
    host: 192.168.0.19
    count: 2
    scan_interval: 60
    name: sam-ghome-mini