
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
api:

# https://www.home-assistant.io/docs/configuration/splitting_configuration/

homeassistant:
  customize: !include customize.yaml

tts: !include config/tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include config/recorder.yaml
mqtt: !include config/mqtt.yaml
logger: !include config/logger.yaml
weather: !include config/weather.yaml
sabnzbd: !include config/sabnzbd.yaml
speedtestdotnet: !include config/speedtestdotnet.yaml
tplink: !include config/tplink.yaml
notify: !include config/notify.yaml
history: !include config/history.yaml
panel_iframe: !include config/panel_iframe.yaml
binary_sensor: !include_dir_merge_list config/binary_sensors
# influxdb: !include config/influxdb.yaml
  