
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
api:

# https://www.home-assistant.io/docs/configuration/splitting_configuration/

homeassistant:
  customize: !include customize.yaml


tts: !include config/tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder: !include config/recorder.yaml
mqtt: !include config/mqtt.yaml
logger: !include config/logger.yaml
weather: !include config/weather.yaml
sabnzbd: !include config/sabnzbd.yaml
speedtestdotnet: !include config/speedtestdotnet.yaml
tplink: !include config/tplink.yaml


sensor:
  # # https://www.home-assistant.io/integrations/worldclock/
  # - platform: worldclock
  #   time_zone: Africa/Johannesburg
  #   name: worldclock.south_africa

notify:
  # https://www.home-assistant.io/integrations/pushover/
  - name: Pushover - Richard (Dev)
    platform: pushover
    api_key: !secret pushover_richard_api_dev
    user_key: !secret pushover_richard_user
  - name: Pushover - Richard
    platform: pushover
    api_key: !secret pushover_richard_api
    user_key: !secret pushover_richard_user
  - name: Pushover - Kelsie
    platform: pushover
    api_key: !secret pushover_kelsie_api
    user_key: !secret pushover_kelsie_user

# https://www.home-assistant.io/integrations/history/
history:
  exclude:
    domains:
      - updater
      - persistent_notification
    entities:
      - sensor.worldclock_south_africa
      - weather.brentwood

# https://www.home-assistant.io/integrations/panel_iframe/
panel_iframe:
  home_control:
    title: 'Home Control'
    url: 'https://apps.richardn.ca/home-control'
    icon: mdi:playlist-check
  # sonarr:
  #   title: 'Sonarr'
  #   url: 'http://nas.richardn.ca:8989/'
  #   icon: mdi:television
  # radarr:
  #   title: 'Radarr'
  #   url: 'http://nas.richardn.ca:7878/'
  #   icon: mdi:television
  # grafana:
  #   title: 'Grafana'
  #   url: 'http://nas.richardn.ca:3000/'
  #   icon: mdi:chart-bell-curve-cumulative

# Example configuration.yaml entry
binary_sensor:
  - platform: mqtt
    name: "Basement Door"
    state_topic: "tele/sonoff_rf/RESULT"
    payload_on: "CD6AC6"
    device_class: door
    value_template: '{{ value_json.RfReceived.Data }}'
    off_delay: 15

  - platform: mqtt
    name: "Front Door"
    state_topic: "tele/sonoff_rf/RESULT"
    payload_on: "016736"
    device_class: door
    value_template: '{{ value_json.RfReceived.Data }}'
    off_delay: 60

  - platform: mqtt
    name: "Back Door"
    state_topic: "tele/sonoff_rf/RESULT"
    payload_on: "015836"
    device_class: door
    value_template: '{{ value_json.RfReceived.Data }}'
    off_delay: 60

  - platform: mqtt
    name: "Spare Room Door"
    state_topic: "tele/sonoff_rf/RESULT"
    payload_on: "BB3AC6"
    device_class: door
    value_template: '{{ value_json.RfReceived.Data }}'
    off_delay: 15

  - platform: mqtt
    name: "Downstairs Toilet"
    state_topic: "tele/sonoff_rf/RESULT"
    payload_on: "015786"
    device_class: door
    value_template: '{{ value_json.RfReceived.Data }}'
    off_delay: 120

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_db
  max_retries: 3
  default_measurement: state
  