title: Brentwood
views:
  - badges:
      - entity: person.richard_niemand
      - entity: person.sam
      - entity: person.kelsie
    cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: switch.master_bedroom
                icon: 'mdi:light-switch'
                name: Master
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: switch.front_door
                icon: 'mdi:light-switch'
                name: Front Door
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.master_bedroom
                icon: 'mdi:bed-king'
                name: Master
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.sam_s_light
                icon: 'mdi:baby-carriage'
                name: Sam
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.lounge_desk_lamp
                name: Lounge
                icon: 'mdi:desk'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.lounge_floor_lamp
                name: Lounge
                icon: 'mdi:television-classic'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.dining_floor_lamp
                name: Dining
                icon: 'mdi:food'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.external
                icon: 'mdi:home'
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.spare_room
                icon: 'mdi:bunk-bed'
                name: Spare
              - type: button
                tap_action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.spare_room
                    brightness_pct: 5
                hold_action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.spare_room
                    brightness_pct: 90
                show_icon: true
                show_name: true
                show_state: true
                entity: light.spare_room
                icon: 'mdi:bunk-bed'
                name: Night Light
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.basement_office
                name: Office
                icon: 'mdi:briefcase-outline'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: true
                entity: light.play_area_overhead
                icon: 'mdi:gamepad-square-outline'
                name: Play Area
      - cards:
          - entity: sensor.huawei_nxt_l09_battery_level
            max: 100
            min: 0
            name: Sam
            type: gauge
            unit: '%'
          - entity: sensor.pixel_2_xl_battery_level
            max: 100
            min: 0
            name: Kelsie
            type: gauge
            unit: '%'
          - entity: sensor.pixel_4_xl_battery_level
            max: 100
            min: 0
            name: Richard
            type: gauge
            unit: '%'
        type: horizontal-stack
      - card:
          entity: media_player.living_room_speaker
          type: media-control
        conditions:
          - entity: media_player.living_room_speaker
            state: playing
        type: conditional
      - card:
          entity: media_player.sams_room_speaker
          type: media-control
        conditions:
          - entity: media_player.sams_room_speaker
            state: playing
        type: conditional
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - cards:
          - entity: light.external_lights
            icon: 'mdi:home'
            name: External
            type: light
          - entity: light.back_door
            hold_action:
              action: more-info
            icon: 'mdi:shovel'
            name: Back
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: light.front_door
            hold_action:
              action: more-info
            icon: 'mdi:door'
            name: Front
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
        type: horizontal-stack
      - cards:
          - entity: light.master_bedroom
            icon: 'mdi:bed'
            name: Master
            type: light
          - entity: light.master_bedside
            hold_action:
              action: more-info
            icon: 'mdi:lamp'
            name: Bedside
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: light.master_lamp
            hold_action:
              action: more-info
            icon: 'mdi:floor-lamp'
            name: Floor Lamp
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
        type: horizontal-stack
      - cards:
          - entity: light.spare_room
            icon: 'mdi:bunk-bed-outline'
            name: Spare Room
            type: light
          - entity: light.sam_s_light
            icon: 'mdi:baby-carriage'
            name: Sam's Bed
            type: light
          - entity: light.spare_room
            hold_action:
              action: more-info
            icon: 'mdi:bunk-bed-outline'
            name: Night Light
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
        type: horizontal-stack
      - cards:
          - entity: light.lounge_floor_lamp
            icon: 'mdi:television'
            name: Lounge Lamp
            type: light
          - entity: light.dining_floor_lamp
            icon: 'mdi:food-drumstick-outline'
            name: Dining Lamp
            type: light
          - entity: light.lounge_desk_lamp
            icon: 'mdi:desk'
            name: Lounge Desk
            type: light
        type: horizontal-stack
      - entity: light.hue_white_lamp_1
        type: light
      - entity: light.play_area_overhead
        type: light
    icon: 'mdi:lightbulb-outline'
    path: lights
    title: Lights
  - badges: []
    cards:
      - entity: switch.tv_plug
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
      - entity: switch.master_fan
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
    icon: 'mdi:settings'
    path: automations
    title: Automations
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:volume-high'
    path: media
    title: Media
  - badges: []
    cards:
      - cards:
          - entity: sensor.huawei_nxt_l09_battery_level
            max: 100
            min: 0
            name: Sam
            type: gauge
            unit: '%'
          - entity: sensor.pixel_2_xl_battery_level
            max: 100
            min: 0
            name: Kelsie
            type: gauge
            unit: '%'
          - entity: sensor.pixel_4_xl_battery_level
            max: 100
            min: 0
            name: Richard
            type: gauge
            unit: '%'
        type: horizontal-stack
      - entities:
          - entity: sensor.huawei_nxt_l09_battery_level
            name: Sam
          - entity: sensor.pixel_2_xl_battery_level
            name: Kelsie
          - entity: sensor.pixel_4_xl_battery_level
            name: Richard
        hours_to_show: 24
        refresh_interval: 2
        title: Battery %
        type: history-graph
      - entities:
          - entity: sensor.huawei_nxt_l09_geocoded_location
            name: Sam
          - entity: sensor.kelsie_phone_geocoded_location
            name: Kelsie
          - entity: sensor.pixel_4_xl_geocoded_location
            name: Richard
        title: Device Locations
        type: entities
      - type: entities
        title: Mobile Data
        entities:
          - entity: sensor.kelsie_phone_mobile_rx_gb
          - entity: sensor.kelsie_phone_mobile_tx_gb
          - entity: sensor.pixel_4_xl_mobile_rx_gb
          - entity: sensor.pixel_4_xl_mobile_tx_gb
      - card:
          entities:
            - entity: sensor.pixel_4_xl_battery_health
              name: Battery Health
            - entity: sensor.pixel_4_xl_battery_level
              name: Battery Level
            - entity: sensor.pixel_4_xl_charger_type
              name: Charger Type
          show_header_toggle: false
          title: Richard Phone (Charging)
          type: entities
        conditions:
          - entity: binary_sensor.pixel_4_xl_is_charging
            state: 'on'
        type: conditional
      - card:
          entities:
            - entity: sensor.pixel_2_xl_battery_health
              name: Battery Health
            - entity: sensor.pixel_2_xl_battery_level
              name: Battery Level
            - entity: sensor.pixel_2_xl_charger_type
              name: Charger Type
          show_header_toggle: false
          title: Kelsie Phone (Charging)
          type: entities
        conditions:
          - entity: binary_sensor.pixel_2_xl_is_charging
            state: 'on'
        type: conditional
      - type: entities
        title: WiFi Data
        entities:
          - entity: sensor.kelsie_phone_total_tx_gb
          - entity: sensor.kelsie_phone_total_rx_gb
          - entity: sensor.pixel_4_xl_total_tx_gb
          - entity: sensor.pixel_4_xl_total_rx_gb
          - entity: sensor.sam_phone_total_tx_gb
          - entity: sensor.sam_phone_total_rx_gb
      - card:
          entities:
            - entity: sensor.huawei_nxt_l09_battery_health
              name: Battery Health
            - entity: sensor.huawei_nxt_l09_battery_level
              name: Battery Level
            - entity: sensor.huawei_nxt_l09_charger_type
              name: Charger Type
          show_header_toggle: false
          title: Sam Phone (Charging)
          type: entities
        conditions:
          - entity: binary_sensor.huawei_nxt_l09_is_charging
            state: 'on'
        type: conditional
    icon: 'mdi:cellphone'
    path: phones
    title: Phones
  - badges: []
    cards:
      - card:
          entities:
            - entity: sensor.pixel_2_xl_battery_level
            - entity: binary_sensor.kelsie_phone_mic_muted
            - entity: sensor.kelsie_phone_proximity_sensor
            - entity: binary_sensor.kelsie_phone_speakerphone
            - entity: sensor.kelsie_phone_volume_level_call
            - entity: sensor.pixel_2_xl_phone_state
          title: Kelsie (On Phone)
          type: entities
        conditions:
          - entity: sensor.kelsie_phone_audio_mode
            state: in_call
        type: conditional
    path: testing
    title: Testing
