views:
  - title: Overview
    path: overview
    badges: []
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kids_here
          - entity: input_datetime.test_date
        show_header_toggle: false
        title: Config
  - title: Alerting
    path: alerting
    badges: []
    cards:
      - type: entities
        entities:
          - entity: automation.alert_front_door_early_morning
            name: Front Door
            icon: 'mdi:door'
          - entity: automation.alert_basement_door_early_morning
            name: Basement Door
            icon: 'mdi:briefcase-outline'
          - entity: automation.alert_back_door_early_morning
            name: Back Door
            icon: 'mdi:door-open'
          - entity: automation.alert_boys_room_door_early_morning
            name: Boys Room Door
            icon: 'mdi:bunk-bed'
        title: 'Alerting: Doors (Kids Here)'
        show_header_toggle: false
        state_color: false
      - type: history-graph
        entities:
          - entity: binary_sensor.front_door
          - entity: binary_sensor.basement_door
          - entity: binary_sensor.back_door
          - entity: binary_sensor.boys_room_door
        hours_to_show: 6
        refresh_interval: 1
        title: Doors History
  - title: Sam
    path: sam
    badges: []
    cards:
      - type: entities
        entities:
          - entity: automation.remote_sam_01_top_left
            name: Light Toggle (Top Left)
            icon: 'mdi:toggle-switch'
          - entity: automation.remote_sam_01_top_right
            name: Light 100% (Top Right)
            icon: 'mdi:brightness-7'
          - entity: automation.remote_sam_01_bottom_left
            name: Light 5% (Bottom Left)
            icon: 'mdi:brightness-2'
        title: Bedroom Remote
        show_header_toggle: false
  - title: Kelsie
    path: kelsie
    badges: []
    cards:
      - type: entities
        entities:
          - entity: automation.remote_kelsie_01_a
            name: (A) Toggle Boys Room
            icon: 'mdi:bunk-bed'
          - entity: automation.remote_kelsie_01_b
            name: (B) Night Ligh - Boys Room
            icon: 'mdi:brightness-2'
          - entity: automation.remote_kelsie_01_c
            name: (C) Master Bedroom Wall
            icon: 'mdi:light-switch'
          - entity: automation.remote_kelsie_01_d
            name: (D) Master Bedroom Fan
            icon: 'mdi:fan'
        title: Kelsie's Remote
        show_header_toggle: false
  - title: Basement
    path: basement
    badges: []
    cards:
      - type: entities
        entities:
          - entity: automation.remote_basement_landing_left
            name: (Left) Play Room Ceiling
            icon: 'mdi:gamepad-variant-outline'
          - entity: automation.remote_basement_landing_right
            name: (Right) Storage Nook
            icon: 'mdi:stairs'
        title: Basement Landing
        show_header_toggle: false
      - type: entities
        entities:
          - entity: automation.remote_basement_office_left
            name: (Left) Office Lamp
            icon: 'mdi:briefcase-outline'
          - entity: automation.remote_basement_office_middle
            name: (Middle) Sensi Pot
            icon: 'mdi:oil-lamp'
          - entity: automation.remote_basement_office_right
            name: (Right) Laundry
            icon: 'mdi:washing-machine'
        title: Basement Office
        show_header_toggle: false
