title: Kelsie
views:
  - badges:
      - entity: person.richard_niemand
      - entity: person.richard_niemand
      - entity: person.sam
    cards:
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: call-service
              service: script.master_bedroom_kill_switch
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.master_bedroom
            name: Master
            icon: 'mdi:light-switch'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.master_fan
            name: Fan
            icon: 'mdi:fan'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.master_bedside
            name: Bedside
            icon: 'mdi:lamp'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.master_lamp
            name: Lamp
            icon: 'mdi:floor-lamp'
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: switch.front_door
                name: Kitchen
                icon: 'mdi:door'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.external
                icon: 'mdi:home'
                name: 'Ext: All'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.front_door
                icon: 'mdi:door-closed'
                name: 'Ext: Front'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.back_door
                icon: 'mdi:outdoor-lamp'
                name: 'Ext: Back'
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.ground_floor
                name: 'Ground: All'
                icon: 'mdi:home-floor-g'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.lounge_desk_lamp
                icon: 'mdi:desk'
                name: Desk
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.lounge_floor_lamp
                icon: 'mdi:television-classic'
                name: TV
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.dining_floor_lamp
                icon: 'mdi:food'
                name: Dining
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: script.master_bedroom_kill_switch
                name: 'Master: All'
                icon: 'mdi:bed-empty'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: switch.master_bedroom
                name: 'M: Wall'
                icon: 'mdi:light-switch'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.master_bedside
                name: 'M: Bedside'
                icon: 'mdi:lamp'
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.master_lamp
                name: 'M: Lamp'
                icon: 'mdi:floor-lamp'
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.sam_s_light
                icon: 'mdi:baby-carriage'
                name: Sam's Room
              - type: button
                tap_action: &ref_0
                  action: toggle
                hold_action: &ref_1
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.spare_room
                name: Spare Room
                icon: 'mdi:bunk-bed'
              - type: button
                tap_action: *ref_0
                hold_action: *ref_1
                show_icon: true
                show_name: true
                show_state: false
                entity: light.basement_office
                icon: 'mdi:briefcase-clock-outline'
                name: Office
              - type: button
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                show_icon: true
                show_name: true
                show_state: false
                entity: light.play_area
                icon: 'mdi:gamepad-square-outline'
                name: Play Area
    icon: 'mdi:lightbulb-on-outline'
    path: lights
    title: Lights
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:music-note-eighth'
    path: media
    title: Media
