title: Kelsie
views:
  - badges:
      - entity: person.richard_niemand
      - entity: person.richard_niemand
      - entity: person.sam
    cards:
      - cards:
          - entity: switch.master_bedroom
            hold_action:
              action: call-service
              service: script.master_bedroom_kill_switch
            icon: 'mdi:light-switch'
            name: Master
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: switch.master_fan
            hold_action:
              action: more-info
            icon: 'mdi:fan'
            name: Fan
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: light.master_bedside
            hold_action:
              action: more-info
            icon: 'mdi:lamp'
            name: Bedside
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: light.master_lamp
            hold_action:
              action: more-info
            icon: 'mdi:floor-lamp'
            name: Lamp
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
        type: horizontal-stack
      - entity: switch.china_cabinet
        hold_action:
          action: more-info
        icon: 'mdi:coffee'
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: light.dining_floor_lamp
                icon: 'mdi:food'
                name: Dining
                type: light
              - entity: light.lounge_floor_lamp
                icon: 'mdi:television'
                name: T.V.
                type: light
              - entity: light.lounge_desk_lamp
                icon: 'mdi:desk'
                name: Desk
                type: light
            type: horizontal-stack
          - cards:
              - entity: light.master_bedroom
                icon: 'mdi:bed-king'
                name: Master (Hue)
                type: light
              - entity: light.spare_room
                icon: 'mdi:bunk-bed'
                name: Boys Room
                type: light
              - entity: light.sam_s_light
                icon: 'mdi:bed'
                name: Sam's Room
                type: light
            type: horizontal-stack
          - cards:
              - entity: switch.master_bedroom
                hold_action:
                  action: more-info
                icon: 'mdi:light-switch'
                name: Master (Wall)
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.front_door
                hold_action:
                  action: more-info
                icon: 'mdi:door'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.china_cabinet
                hold_action:
                  action: more-info
                icon: 'mdi:coffee'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:lightbulb-on-outline'
    path: lights
    title: Lights
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:music-note-eighth'
    path: media
    title: Media
