title: Lights
views:
  - title: Running
    path: running
    icon: 'mdi:lightbulb-outline'
    badges: []
    cards:
      - type: entity-filter
        entities:
          - entity: light.back_door
            name: Deck (Ext)
            icon: 'mdi:outdoor-lamp'
          - entity: light.front_door
            name: Front (Ext)
            icon: 'mdi:outdoor-lamp'
          - entity: light.basement_office
            name: Office
            icon: 'mdi:briefcase-outline'
          - entity: light.play_area_overhead
            name: Play Area
            icon: 'mdi:gamepad-variant-outline'
          - entity: light.hue_white_lamp_1_2
            name: Storage Nook
            icon: 'mdi:stairs'
          - entity: light.lounge_desk_lamp
            name: Desk
            icon: 'mdi:desk'
          - entity: light.lounge_floor_lamp
            name: T.V.
            icon: 'mdi:television'
          - entity: light.dining_floor_lamp
            name: Dining
            icon: 'mdi:food'
          - entity: light.sam_s_light
            name: Sam
            icon: 'mdi:bed'
          - entity: light.master_bedside
            name: Bedside
            icon: 'mdi:lamp'
          - entity: light.master_lamp
            name: Floor Lamp
            icon: 'mdi:floor-lamp'
          - entity: light.spare_room
            name: Spare Room
            icon: 'mdi:bunk-bed'
        state_filter:
          - 'on'
        show_empty: false
        card:
          type: glance
          show_state: false
          columns: 3
      - type: entity-filter
        entities:
          - entity: switch.master_bedroom
            name: Master Wall
            icon: 'mdi:light-switch'
          - entity: switch.front_door
            name: Front Door
            icon: 'mdi:door'
          - entity: switch.china_cabinet
            name: China Cab.
            icon: 'mdi:coffee'
        state_filter:
          - 'on'
        show_empty: false
        card:
          type: glance
          show_state: false
          columns: 3
  - title: External
    path: external
    icon: 'mdi:garage'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.external_lights
            icon: 'mdi:home'
            name: External
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.front_door
            name: Front
            icon: 'mdi:outdoor-lamp'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.back_door
            name: Deck
            icon: 'mdi:outdoor-lamp'
  - title: Basement
    path: basement
    icon: 'mdi:home-floor-b'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.basement
            name: All Basement
            icon: 'mdi:home-floor-b'
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.basement_office
            name: Office
            icon: 'mdi:briefcase-outline'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.play_area_overhead
            name: Play Area
            icon: 'mdi:gamepad-variant-outline'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.hue_white_lamp_1_2
            name: Storage Nook
            icon: 'mdi:stairs'
  - title: Ground Floor
    path: ground-floor
    icon: 'mdi:home-floor-1'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.ground_floor
            icon: 'mdi:home-floor-1'
            name: Ground (All)
          - type: light
            entity: light.external_lights
            icon: 'mdi:garage'
            name: External (All)
      - type: horizontal-stack
        title: Ground Floor (Hue)
        cards:
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.lounge_desk_lamp
            icon: 'mdi:desk'
            name: Desk
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.lounge_floor_lamp
            icon: 'mdi:television'
            name: T.V.
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.dining_floor_lamp
            icon: 'mdi:food'
            name: Dining
      - type: horizontal-stack
        title: Switch Based Lights
        cards:
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.china_cabinet
            icon: 'mdi:coffee'
            name: China Cab.
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.front_door
            name: Front Door
            icon: 'mdi:door'
  - title: Upstairs
    path: upstairs
    icon: 'mdi:home-floor-2'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.master_bedroom
            name: Master
            icon: 'mdi:bed-king-outline'
          - type: light
            entity: light.sam_s_room
            name: Sam
            icon: 'mdi:bed'
          - type: light
            entity: light.spare_room
            name: Spare
            icon: 'mdi:bunk-bed'
      - type: horizontal-stack
        title: Master Bedroom
        cards:
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.master_bedside
            name: Bedside
            icon: 'mdi:lamp'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: light.master_lamp
            name: Lamp
            icon: 'mdi:floor-lamp'
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.master_bedroom
            name: Wall
            icon: 'mdi:light-switch'
