views:
  - title: External
    path: external
    icon: 'mdi:home-circle'
    badges: []
    cards:
      - type: light
        entity: light.external_lights
        icon: 'mdi:home'
        name: External
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: call-service
              service: light.toggle
              service_data:
                entity_id: light.external_lights
            entity: light.external_lights
            icon: 'mdi:toggle-switch'
            name: On / Off
            hold_action:
              action: more-info
          - type: button
            tap_action:
              action: toggle
            entity: light.front_door
            name: Ext. Front
            icon: 'mdi:outdoor-lamp'
          - type: button
            tap_action:
              action: toggle
            entity: light.back_door
            name: Ext. Back
            icon: 'mdi:coach-lamp'
  - title: Basement
    path: basement
    icon: 'mdi:home-floor-b'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.basement_office
            name: Office
            icon: 'mdi:briefcase-outline'
          - type: light
            entity: light.laundry
            name: Laundry
            icon: 'mdi:washing-machine'
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.play_area_overhead
            name: Play Area
            icon: 'mdi:gamepad-variant-outline'
          - type: light
            entity: light.hue_white_lamp_1_2
            name: Storage Nook
            icon: 'mdi:stairs'
      - type: button
        tap_action:
          action: toggle
        entity: switch.basement_sensi_pot
        name: Sensi Pot
        icon: 'mdi:oil-lamp'
  - title: Ground Floor
    path: ground-floor
    icon: 'mdi:home-floor-g'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.lounge_floor_lamp
            name: T.V. Lamp
            icon: 'mdi:television'
          - type: light
            entity: light.dining_floor_lamp
            name: Dining
            icon: 'mdi:food-fork-drink'
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.lounge_desk_lamp
            name: Desk
            icon: 'mdi:desk'
          - type: light
            entity: light.external_lights
            name: External
            icon: 'mdi:home'
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: toggle
            entity: switch.front_door
            name: Kitchen Wall
            icon: 'mdi:light-switch'
          - type: button
            tap_action:
              action: toggle
            entity: switch.china_cabinet
            name: China Cab.
            icon: 'mdi:coffee'
  - title: Upstairs
    path: upstairs
    icon: 'mdi:home-floor-1'
    badges: []
    cards:
      - type: vertical-stack
        title: Master Bedroom
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.master_bedroom
                name: Master Hues
                icon: 'mdi:bed-king'
              - type: button
                tap_action:
                  action: toggle
                entity: light.master_bedside
                name: Bedside
                icon: 'mdi:lamp'
              - type: button
                tap_action:
                  action: more-info
                entity: light.master_lamp
                name: Floor
                icon: 'mdi:floor-lamp'
                hold_action:
                  action: toggle
          - type: horizontal-stack
            cards:
              - type: button
                tap_action:
                  action: toggle
                entity: switch.master_bedroom_light_switch
                name: Master Wall
                icon: 'mdi:light-switch'
              - type: button
                tap_action:
                  action: toggle
                entity: switch.master_fan
                name: Master Fan
                icon: 'mdi:fan'
      - type: horizontal-stack
        title: Sams Room
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: light.sam_s_room
            name: Toggle
            icon: 'mdi:bed'
            show_state: false
            hold_action:
              action: toggle
            show_name: true
          - type: button
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                brightness_pct: 5
                entity_id: light.sam_s_light
            entity: light.sam_s_light
            name: Night Light
            icon: 'mdi:brightness-3'
            hold_action:
              action: toggle
            show_state: false
            show_icon: true
            show_name: true
          - type: button
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                brightness_pct: 100
                entity_id: light.sam_s_light
            entity: light.sam_s_light
            name: Bright
            icon: 'mdi:brightness-5'
            hold_action:
              action: toggle
            show_state: false
            show_name: true
      - type: horizontal-stack
        title: Boys Room
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: light.boys_room
            icon: 'mdi:bunk-bed'
            hold_action:
              action: toggle
            show_name: true
            name: Toggle
          - type: button
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                brightness_pct: 5
                entity_id: light.boys_room
            entity: light.boys_room
            icon: 'mdi:brightness-3'
            hold_action:
              action: toggle
            show_name: true
            name: Night Light
          - type: button
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                brightness_pct: 100
                entity_id: light.boys_room
            entity: light.boys_room
            name: Bright
            icon: 'mdi:brightness-5'
            hold_action:
              action: toggle
            show_name: true
title: Lights
