title: Richard
views:
  - badges:
      - entity: person.kelsie
      - entity: person.richard_niemand
      - entity: person.sam
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.pixel_4_xl_is_charging
            state: 'on'
        card:
          type: vertical-stack
          title: Richard-Pixel 4 XL
          cards:
            - type: entities
              entities:
                - entity: sensor.pixel_4_xl_charger_type
                - entity: sensor.pixel_4_xl_phone_state
                - entity: sensor.pixel_4_xl_geocoded_location
                - entity: sensor.pixel_4_xl_battery_level
              show_header_toggle: false
            - type: history-graph
              entities:
                - entity: sensor.pixel_4_xl_battery_level
              hours_to_show: 24
              refresh_interval: 0
      - type: conditional
        conditions:
          - entity: binary_sensor.updater
            state: 'on'
        card:
          type: button
          tap_action:
            action: toggle
          hold_action:
            action: more-info
          show_icon: true
          show_name: true
          show_state: false
          entity: binary_sensor.updater
      - type: horizontal-stack
        cards:
          - type: button
            tap_action: &ref_0
              action: toggle
            hold_action: &ref_1
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.master_bedroom
            name: Master Wall
            icon: 'mdi:bed'
          - type: button
            tap_action: *ref_0
            hold_action: *ref_1
            show_icon: true
            show_name: true
            show_state: false
            entity: switch.master_fan
            name: Master Fan
            icon: 'mdi:fan'
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:music-note-eighth'
    path: media
    title: Media
