title: Richard
views:
  - badges:
      - entity: person.kelsie
      - entity: person.richard_niemand
      - entity: person.sam
    cards:
      - cards:
          - entity: switch.master_bedroom
            hold_action:
              action: more-info
            icon: 'mdi:bed'
            name: Master Wall
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - entity: switch.master_fan
            hold_action:
              action: more-info
            icon: 'mdi:fan'
            name: Master Fan
            show_icon: true
            show_name: true
            show_state: false
            tap_action:
              action: toggle
            type: button
          - type: button
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: binary_sensor.updater
        type: horizontal-stack
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: binary_sensor.basement_door
            name: Basement
          - type: button
            tap_action:
              action: more-info
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: binary_sensor.front_door
            name: Front
          - type: button
            tap_action:
              action: more-info
            hold_action:
              action: more-info
            show_icon: true
            show_name: true
            show_state: false
            entity: binary_sensor.back_door
            name: Back
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:music-note-eighth'
    path: media
    title: Media
