title: Richard
views:
  - badges:
      - entity: person.kelsie
      - entity: person.richard_niemand
      - entity: person.sam
    cards:
      - cards:
          - cards:
              - entity: switch.master_bedroom
                hold_action:
                  action: call-service
                  service: script.master_bedroom_kill_switch
                icon: 'mdi:light-switch'
                name: Master
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.master_fan
                hold_action:
                  action: more-info
                icon: 'mdi:fan'
                name: Fan
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.master_bedside
                hold_action:
                  action: more-info
                icon: 'mdi:lamp'
                name: Bedside
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.master_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:floor-lamp'
                name: Lamp
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - entity: sensor.pixel_4_xl_battery_level
            max: 100
            min: 0
            name: Richard
            type: gauge
          - entity: sensor.pixel_2_xl_battery_level
            max: 100
            min: 0
            name: Kelsie
            type: gauge
          - entity: sensor.huawei_nxt_l09_battery_level
            max: 100
            min: 0
            name: Sam
            type: gauge
        type: horizontal-stack
    icon: 'mdi:home'
    path: home
    title: Home
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: switch.front_door
                hold_action:
                  action: more-info
                icon: 'mdi:door'
                name: Kitchen
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.external
                hold_action:
                  action: more-info
                icon: 'mdi:home'
                name: 'Ext: All'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.front_door
                hold_action:
                  action: more-info
                icon: 'mdi:door-closed'
                name: 'Ext: Front'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.back_door
                hold_action:
                  action: more-info
                icon: 'mdi:outdoor-lamp'
                name: 'Ext: Back'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - cards:
              - entity: light.ground_floor
                hold_action:
                  action: more-info
                icon: 'mdi:home-floor-g'
                name: 'Ground: All'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.lounge_desk_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:desk'
                name: Desk
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.lounge_floor_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:television-classic'
                name: TV
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.dining_floor_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:food'
                name: Dining
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - cards:
              - entity: script.master_bedroom_kill_switch
                hold_action:
                  action: more-info
                icon: 'mdi:bed-empty'
                name: 'Master: All'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: switch.master_bedroom
                hold_action:
                  action: more-info
                icon: 'mdi:light-switch'
                name: 'M: Wall'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.master_bedside
                hold_action:
                  action: more-info
                icon: 'mdi:lamp'
                name: 'M: Bedside'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.master_lamp
                hold_action:
                  action: more-info
                icon: 'mdi:floor-lamp'
                name: 'M: Lamp'
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
          - cards:
              - entity: light.sam_s_light
                hold_action:
                  action: more-info
                icon: 'mdi:baby-carriage'
                name: Sam's Room
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.spare_room
                hold_action:
                  action: more-info
                icon: 'mdi:bunk-bed'
                name: Spare Room
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.basement_office
                hold_action:
                  action: more-info
                icon: 'mdi:briefcase-clock-outline'
                name: Office
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
              - entity: light.play_area
                hold_action:
                  action: more-info
                icon: 'mdi:gamepad-square-outline'
                name: Play Area
                show_icon: true
                show_name: true
                show_state: false
                tap_action:
                  action: toggle
                type: button
            type: horizontal-stack
        type: vertical-stack
      - type: button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        entity: switch.china_cabinet
        icon: 'mdi:coffee'
    icon: 'mdi:lightbulb-on-outline'
    path: lights
    title: Lights
  - badges: []
    cards:
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.sams_room_speaker
        type: media-control
    icon: 'mdi:music-note-eighth'
    path: media
    title: Media
  - badges: []
    cards:
      - cards:
          - cards:
              - entity: sensor.pixel_4_xl_battery_level
                max: 100
                min: 0
                name: Richard
                type: gauge
              - entity: sensor.pixel_2_xl_battery_level
                max: 100
                min: 0
                name: Kelsie
                type: gauge
              - entity: sensor.huawei_nxt_l09_battery_level
                max: 100
                min: 0
                name: Sam
                type: gauge
            type: horizontal-stack
          - entities:
              - entity: sensor.pixel_4_xl_battery_level
                name: Richard
              - entity: sensor.pixel_2_xl_battery_level
                name: Kelsie
              - entity: sensor.huawei_nxt_l09_battery_level
                name: Sam
            hours_to_show: 24
            refresh_interval: 0
            type: history-graph
        title: Phone Battery %
        type: vertical-stack
    icon: 'mdi:phone'
    path: phones
    title: Phones
