# https://www.home-assistant.io/integrations/sabnzbd/

api_key: !secret sabnzbd_apikey
host: !secret sabnzbd_host
port: !secret sabnzbd_port
name: nas_sab
sensors:
  - current_status
  - speed
  - queue_size
  - queue_remaining
  - disk_size
  - disk_free
  - queue_count
  - day_size
  - week_size
  - month_size
  - total_size