- platform: mqtt
  name: "Sam Bedroom Door"
  state_topic: "tele/sonoff_rf/RESULT"
  payload_on: "EF8EC6"
  device_class: door
  value_template: '{{ value_json.RfReceived.Data }}'
  off_delay: 15