- platform: mqtt
  name: "Spare Room Door"
  state_topic: "tele/sonoff_rf/RESULT"
  payload_on: "BB3AC6"
  device_class: door
  value_template: '{{ value_json.RfReceived.Data }}'
  off_delay: 15