- platform: mqtt
  name: "Guest Toilet Door"
  state_topic: "tele/sonoff_rf/RESULT"
  payload_on: "015786"
  device_class: door
  value_template: '{{ value_json.RfReceived.Data }}'
  off_delay: 120